name: Endor Labs Dependency and Secrets Scan
on:
  workflow_dispatch:
  
jobs:
  # Job 1: San on PR
  scan-pr:
    runs-on: ubuntu-latest
    permissions:
      security-events: write # Used to upload Sarif artifact to GitHub
      contents: read # Used to check out a private repository
      actions: read # Required for private repositories to upload Sarif files. GitHub Advanced Security licenses are required.
      id-token: write # Used for keyless authentication with Endor Labs
      issues: write # Required to automatically comment on PRs for new policy violations
      pull-requests: write # Required to automatically comment on PRs for new policy violations
    
    # Checkout repo and build
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'microsoft'
        java-version: '17'
    - name: Build Package
      run: mvn clean install
      
  # Job 2: scan-main
  scan-main:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      repository-projects: read
      pull-requests: read
      contents: read
      security-events: write
    
    name: endorctl-scan
    steps:
    - uses: actions/checkout@v3
    - name: 'Endor Labs Scan Push to main'
      uses: endorlabs/github-action@main
      with:
        namespace: 'kriti-learn'
        api.key: ${{ secrets.KEY }}
        api.secret: ${{ secrets.SECRET }}
        scan_dependencies: true
        pr: false
        scan_summary_output_type: 'table'
    
 
    
